name: HycraftQuestsAddons
authors:
  - JustOp_
version: '1.0-SNAPSHOT'
main: fr.justop.hycraftQuestsAddons.HycraftQuestsAddons
api-version: '1.20'
depend:
  - BeautyQuests
  - Citizens

commands:
  registerPlayerGoats:
    description: initialise la Hash Map

permissions:
  hycraft.questsaddons.hasfoundgoats:
    description: 'Est donné dans la quête: les chèvres de M.Sevin'