name: HycraftQuestsAddons
authors:
  - JustOp_
version: '1.0-SNAPSHOT'
main: fr.justop.hycraftQuestsAddons.HycraftQuestsAddons
api-version: '1.20'
depend:
  - BeautyQuests
  - Citizens

commands:
  registerPlayerGoats:
    description: initialise la Hash Map
  startStage4:
    description: force le début d'un dialogue
  endDiplo:
    description: tkt frr
  q:
    description: pk pas

permissions:
  hycraft.questsaddons.hasfoundgoats:
    description: 'Est donné dans la quête: les chèvres de M.Sevin'